## MODIS land cover type classification (1 and 3) producr MCD12Q1
## Layers in https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd12q1
LCT1lookuptable <- data.frame(id=c(0:16, 255),
                              name=c("Water",
                                     "Evergreen Needleleaf forest",
                                     "Evergreen Broadleaf forest",
                                     "Deciduous Needleleaf forest",
                                     "Deciduous Broadleaf forest",
                                     "Mixed forest",
                                     "Closed shrublands",
                                     "Open shrublands",
                                     "Woody savannas",
                                     "Savannas",
                                     "Grasslands",
                                     "Permanent wetlands",
                                     "Croplands",
                                     "Urban and built-up",
                                     "Cropland/Natural vegetation mosaic",
                                     "Snow and ice",
                                     "Barren or sparsely vegetated",
                                     "Fill Value/Unclassified"),
                              stringsAsFactors = FALSE)

LCT3lookuptable <- data.frame(id=c(0:10, 255),
                              name=c("Water",
                                     "Grasses/Cereal crops",
                                     "Shrubs",
                                     "Broad-leaf crops",
                                     "Savanna",
                                     "Evergreen Broadleaf forest",
                                     "Deciduous Broadleaf forest",
                                     "Evergreen Needleleaf forest",
                                     "Deciduous Needleleaf forest",
                                     "Non-vegetated",
                                     "Urban",
                                     "Fill Value/Unclassified"),
                              stringsAsFactors = FALSE)
